// import './js/render-popular-movies';
import './js/home-modal-js/homeModalJS';
import './js/advice&team-modal/create-advice-form';
import './js/advice&team-modal/advice-films-by-ganre';
import './js/advice&team-modal/open-close-team-modal';
import './js/popular-movies/index';
import './js/advice&team-modal/advertising';
import './js/home-modal-js/homeModalJS';
import './js/keyword-search-film/index';
import './js/spinner-js/spinner';
import './js/home-modal-js/closingModal';
import './js/local-storage/local-storage';
import './js/theme-change/day-night';
import './js/pagination/pagination';
import './js/firebase/modal-auth';
import './js/firebase/firebase-auth';
